### ISSUE TITLE
Doesn't work in firefox

### ISSUE THREAD

**Issue by vipul30** [esotericmynd/jquery-timecube#4]
I get this error in firefox

ReferenceError: event is not defined timecube.jquery.js:240:4

It works fine using safari and chrome.  Any suggestions?  Thanks,

**Comment by xiedx** [comment]
因为css兼容问题，在-webkit-transition-property的地方加上-moz-transition-property和-moz-transition-duration，还有 base.$container[0].style.webkitTransform=xxxxx后加上 base.$container[0].style.MozTransform=xxxxxx，还有个问题就是firfox的日期写法应该是var str ='2012-08-12 23:13:15';
str = str.replace(/-/g,"/");
var date = new Date(str );

**Comment by esotericmynd** [comment]
This is for archival / forking purposes only. It is not supported.
